<a href="https://colab.research.google.com/github/aadityasomani/Aadi/blob/master/2021_10_31_AdityaSomani_Project14ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Instructions

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the following lessons:

1. While Loop, Data-Type Conversion and Conditional Statements.

2. Improving the Algorithm (Functions).


---

#### Getting Started

Follow the steps described below to solve the project:

1. Click on the link provided below to open the Colab file for this project.
   
   https://colab.research.google.com/drive/1py225qDjnGFokkG1PitXA7i4lchXnc-Z
   
2. Create the duplicate copy of the Colab file. Here are the steps to create the duplicate copy:

    - Click on the **File** menu. A new drop-down list will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/0_file_menu.png' width=500>

    - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/1_create_colab_duplicate_copy.png' width=500>

     - After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project12** format. 

3. Now, write your code in the prescribed code cells.

---

### Activities


  

#### Activity 1: Guess the Number

Create a function which takes a random number $n$ between `10` and `20` (including both) and checks whether the player has guessed the number correctly or not.

**For example:** 

- For random number $n = 10$, 
    
    - If the player guesses a number less than `n`, Print `You guessed small!, The number is 10`.

    - If the player guesses a number greater `n`, Print `You guessed high!, The number is 10`.

    - If the player guesses a number equal to `n`, Print `Correct Guess!, The number is 10`. 


Follow the steps given below to achieve the desired result:

- **Step 1**: Create a function, let's say `num_guess()` and pass $n$ as a parameter in this function, where $n$ is a random number between `10` and `20`.

- **Step 2**: Inside the function,

    - Ask the user to enter a number between `10` and `20`. Convert the data type of user input to integer and then store it in a variable `user_guess`.

    - If `user_guess` is greater than $n$, return `You guessed high!, The number is 'n'`.

    - Elif `user_guess` is less than $n$, return `You guessed small!, The number is 'n'`.

    - Elif `user_guess` is equal to $n$, return `Correct Guess!, The number is 'n'`.  

- **Step 4**: Generate a random integer between `10` and `20` using the `randint()` function of the `random` module and store this in a variable `rand_num`.

-  **Step 5**: Call the function `num_guess()` and pass `rand_num` as a parameter inside this function.

In [ ]:
# Import random module
import random
# Create the 'num_guess()' function and pass  𝑛  as a parameter
def num_guess(n):
    user_guess=int(input("Enter a number between 10 and 20: "))
    if user_guess > n:
        return 'You guessed high!' , n
    elif user_guess<n:
        return 'You guessed small!' , n
    else:
        return 'Correct Guess!' , n
  # Ask the user to enter a number between 10 and 20 and store it in a variable 'user_guess'.

  # If 'user_guess' is greater than  𝑛 , return 'You guessed high!' and 'n'.


  # If 'user_guess' is lower than  𝑛 , return 'You guessed small!' and 'n'.


  # If 'user_guess' is equal to  𝑛 , return 'Correct Guess!' and 'n'.



# Generate a random integer between 10 and 20 using randint() function and store it in a variable 'rand_num'
rand_num=random.randint(10,20)
# Call the function num_guess() and pass 'rand_num' as a parameter inside this function
num_guess(rand_num)

Enter a number between 10 and 20: 20


('You guessed high!', 18)

---

#### Activity 2: Calculator

Create a function which lets user to input the choice of arithmetic operation they want to perform on a pair of numerical values and returns the appropriate result.

Follow the steps given below to achieve the desired result:

  - **Step 1**: Create a function `calculator()` which takes two inputs `num1` and `num2`.

  - **Step 2**: Ask the user to input the operation that the user wants to perform by printing the following choices:
```
  Enter 1 for Addition.
  Enter 2 for Subtraction.
  Enter 3 for Multiplication.
  Enter 4 for Division.
```

  - **Step 3**: Store the number entered by user in a variable `choice`.
  
  - **Step 4**: Use `if-else` statements to check user input. If `choice == "1"`, then perform addition and print the result using `print(num1 + num2)`. 
  
   Else if `choice == "2"`, perform subtraction and print the result using `print(num1 - num2)`. Perform similar activity for multiplication and division.

  - **Step 5:** Call the `calculator()` function by passing two integers.


In [ ]:
# Step 1: Define function 'calculator()'
def calculator(num1,num2):
    choice=int(input("Enter 1 for Addition. \n Enter 2 for Subtraction.\nEnter 3 for Multiplication.\nEnter 4 for Division."))
    if choice==1:
        print(num1+num2)
    elif choice==2:
        print(num1-num2)
    elif choice==3:
        print(num1*num2)
    elif choice==4:
        print(num1/num2)
  # Step 2: Ask user input
    
    # Step 3: Store user input in a variable 'choice'
    
    # Step 4: Use if-else statement to check the value of 'choice' variable
    

# Call the function by passing two integers. for e.g: calculator(4,5)
calculator(4,5)


Enter 1 for Addition. 
 Enter 2 for Subtraction.
Enter 3 for Multiplication.
Enter 4 for Division.3
20


---

Extra Submission

In [ ]:
import random
import numpy as np
inputs = np.zeros(shape=(3, 3, 2), dtype=int)
inputs


array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [3]:
import random
import numpy as np
last_1 = 0
last_2 = 0
inputs = np.zeros(shape=(3, 3, 2), dtype=int)
inputs
def update_inputs(current):
    global last_1,last_2
    if inputs[last_2][last_1][0]==current:
        inputs[last_2][last_1][1]=1

    else:
        inputs[last_2][last_1][0]=current
        inputs[last_2][last_1][1]=0
        
    last_2,last_1=last_1,current
    print(inputs)

def prediction():
    if inputs[last_2][last_1][1]==1:
        if inputs[last_2][last_1][0]==0:
            return 1
        elif inputs[last_2][last_1][0]==1:
            return 2
        else:
            return 0
       # return inputs[last_2][last_1][0]    
    else:
        return random.randint(0,2)

scores=[0,0]
def update_scores(user_input,pred):
  if user_input == 0:
    if pred == 0:
      print("\nYou played ROCK, computer played ROCK.")
      print("\nComputer Score: ", scores[0], "\nYour Score: ", scores[1])
    elif pred == 1:
      print("\nYou played ROCK, computer played PAPER.")
      scores[0] += 1
      print("\nComputer Score: ", scores[0], "\nYour Score: ", scores[1])
    else:
      print("\nYou played ROCK, computer played SCISSORS.")
      scores[1] += 1
      print("\nComputer Score: ", scores[0], "\nYour Score: ", scores[1])
  
  # Code for Situation 4, 5 and 6.
  elif user_input == 1:
    if pred == 1:
      print("\nYou played PAPER, computer played PAPER.")
      print("\nComputer Score: ", scores[0], "\nYour Score: ", scores[1])
    elif pred == 0:
      print("\nYou played PAPER, computer played ROCK.")
      scores[1] += 1
      print("\nComputer Score: ", scores[0], "\nYour Score: ", scores[1])
    else:
      print("\nYou played PAPER, computer played SCISSORS.")
      scores[0] += 1
      print("\nComputer Score: ", scores[0], "\nYour Score: ", scores[1])

  else:
    if pred==2:
        print("\nYou played SCISSORS, computer played SCISSORS.")
        print("\nComputer Score: ", scores[0], "\nYour Score: ", scores[1])
    elif pred == 1:
        print("\nYou played SCISSORS, computer played ROCK.")
        scores[0] += 1
        print("\nComputer Score: ", scores[0], "\nYour Score: ", scores[1])
    else:
        print("\nYou played SCISSORS, computer played PAPER.")
        scores[1] += 1
        print("\nComputer Score: ", scores[0], "\nYour Score: ", scores[1])


def reset():
    for i in range(3):
        for j in range(3):
            for k in range(2):
                inputs[i][j][k]=0
    for i in range(2):
        scores[i]=0



def gameplay():
    reset()
    valid_entries=['0','1','2']
    while True:
        player_input = input("Enter 0 for ROCK, 1 for PAPER and 2 for SCISSORS: ")
        while player_input not in valid_entries:
            print("Invalid Entry. ")
            player_input = input("Enter 0 for ROCK, 1 for PAPER and 2 for SCISSORS: ")
        predict=prediction()
        player_input=int(player_input)
        update_inputs(player_input)
        update_scores(player_input,predict)
        if scores[0]==15:
            print("Computer Wins.")
            break
        elif scores[1]==15:
            print("Player Wins.")
            break
gameplay()

Enter 0 for ROCK, 1 for PAPER and 2 for SCISSORS: 0
[[[0 1]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]

You played ROCK, computer played PAPER.

Computer Score:  1 
Your Score:  0
Enter 0 for ROCK, 1 for PAPER and 2 for SCISSORS: 1
[[[1 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]

You played PAPER, computer played PAPER.

Computer Score:  1 
Your Score:  0
Enter 0 for ROCK, 1 for PAPER and 2 for SCISSORS: 2
[[[1 0]
  [2 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]

You played SCISSORS, computer played ROCK.

Computer Score:  2 
Your Score:  0
Enter 0 for ROCK, 1 for PAPER and 2 for SCISSORS: 0
[[[1 0]
  [2 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 1]]

 [[0 0]
  [0 0]
  [0 0]]]

You played ROCK, computer played PAPER.

Computer Score:  3 
Your Score:  0
Enter 0 for ROCK, 1 for PAPER and 2 for SCISSORS: 1
[[[1 0]
  [2 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 1]]

 [[1 0]
  [0 0]
  [0 0]]]

You played PAPER, computer played SCI

### Submitting the Project

Follow the steps described below to submit the project.

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>


3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project12**) of the notebook will get copied 

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project12** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>


---