<a href="https://colab.research.google.com/github/aadityasomani/Aadi/blob/master/Lesson_74_Numerical_Algorithms_Aditya.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lesson 74: Numerical Algorithms


---

### Teacher-Student Tasks

In this class, we will learn how to perform computational tasks using the numerical algorithms.

---

#### Task 1: Interpolation

**Interpolation** or linear interpolation is usually the process of estimating unknown values that fall between known values. It is the estimation of an unknown value that falls within two known values. 

For e.g: within points 1 and 2, we may interpolate and find points 1.33 and 1.69.

Linear interpolation is used in various disciplines like statistical, economics, price determination, etc. It is used to fill the gaps in the statistical data for the sake of continuity of information. 

By using the following formula we can linearly interpolate the given data point:
$$\text{Linear Interpolation:} y(x) = y1 + (x - x1)\frac{(y2-y1)}{(x2-x1)}$$

Here,
-  $(x1, y1)$ are the coordinates of the first data point.
- $(x2,y2)$ are coordinates of the second data point.
- $x$ is the point on which we perform the interpolation.
- $y$ is the interpolated value.

Let us try to understand this with the help of an example.

We have the following data values where $x$ denotes the number and $y$ is the function of the square root of $x$. Our task is to find the square root of `5.5` (i.e `x` = `5.5`)

|x|y = f(x) = $\sqrt{x}$|
|-|-|
|1|1|
|2|1.4141|
|3|1.7320|
|4|2|
|5|2.2360|
|6|2.4494|

**Steps:**

1. Find the two adjacent  $(x1, y1)$ ,$(x2,y2)$ from the $x$ i.e. `(5, 2.2360)` and `(6, 2.4494)`.
2. Put the values in the equation:
$$y(x) = y1 + (x - x1)\frac{(y2-y1)}{(x2-x1)}$$
3. After putting values:
  $$y(x) = 2.2360 + (5.5 - 5)\frac{(2.4494-2.2360)}{6-5}$$

  we get $y = 2.3427$

At $x = 5.5$ the value of $Y$ will be `2.3427`. So by using linear interpolation we can easily determine the value of a function between two intervals.

We can also find the interpolation value by applying the formula in Python.

In [ ]:
# S1.1: Create a function that calculates y value using formula.
def interpolation(d, x):
    output = d[0][1] + (x - d[0][0]) * ((d[1][1] - d[0][1])/(d[1][0] - d[0][0]))
  
    return output
  
# Store x1, y1, x2, y2 values as list
data=[[5, 2.2360],[6, 2.4494]]

# Create a variable to store the 'x' value.
x_data = 5.5
  
# Finding the interpolation
print("The value of y for x = {} is".format(x_data),
             interpolation(data, x_data))

The value of y for x = 5.5 is 2.3427


Thus, we obtained the desired value by implementing the formula using Python.

**Using scipy.interpolate.interp1d**

Similarly, we can achieve linear interpolation using a `scipy` library function called `interpolate.interp1d`


- The `interp1d` class in the `scipy.interpolate` is used to interpolate 1D function.
- An instance of this class is created by passing the 1-D vectors comprising the data.

  **Syntax:**`scipy.interpolate.interp1d(x, y)`

  where, 
  - `x` and `y`are arrays of real values.
 - The length of `y` along the interpolation axis must be equal to the length of `x`.

Let’s have a random dataset :

- `x` = `[1, 2, 3, 4, 5]`
- `y` = `[11, 2.2, 3.5, -88, 1]` 

We want to find the value of `y` at point `2.5`

In [ ]:
# S2.2: Implementation of Linear Interpolation using Python
# Import library
from scipy.interpolate import interp1d

# Create 'x' and 'y' arrays.
x = [1, 2, 3, 4, 5] 
y = [11, 2.2, 3.5, -88, 1] 
  
# Test value
interpolate_x = 2.5
  
# Find the interpolation
y_interp = interp1d(x, y)
print("Value of y at x = {} is".format(interpolate_x),
      y_interp(interpolate_x))

Value of y at x = 2.5 is 2.85


Thus, we can use both formula approach or `interp1d()` function to interpolate value for a known data.

---

#### Task 2: Quadrature rules

**What is a Quadrature rule?**

- A quadrature rule is an approximation of the definite integral of a function, usually stated as a weighted sum of function values at specified points within the domain of integration.

- An $n$-point Gaussian quadrature rule is a quadrature rule which generated exact result for polynomials of degree $2n − 1$ or less by a suitable choice of the nodes $x_i$ and weights $w_i$ for i = 1, ..., $n$

`scipy.integrate.quadrature()` function computes a definite integral using Gaussian quadrature.

**Syntax:** `scipy.integrate.quadrature(func, a, b)`

 where, 
 - `func`: A Python function or method to integrate.
 - `a`: Lower limit of integration.
 - `b`: Upper limit of integration.

Let us derive the gaussian quadrature approximation to integral function from limit `a` to `b` by using `quadrature()` function.


In [ ]:
# S2.1: Get the gaussian quadrature approximation to integral function from limit 0.0 to 1.8
# import scipy.integrate
from scipy import integrate

func = lambda x: x**8 + x**4

# use scipy.integrate.quadrature() method
output = integrate.quadrature(func, 0.0, 1.8)

print(output)


(25.81905715199999, 0.0)


In the output, we obtained two values:
 - First value is the Gaussian quadrature approximation (within tolerance) to integral.
 - Second value is error or the difference between last two estimates of the integral.

---

#### Task 3: Eigenvalues and Eigenvectors

**Definition:**


Let $A$ be a square matrix. A non-zero vector $v$ is an eigenvector for $A$  with eigenvalue $\lambda$  if:

$$Av=\lambda v$$

Rearranging the equation, we see that $v$ is a solution of the homogeneous system of equations:

$$(A-\lambda I)v=0$$

Where $I$ is the identity matrix of size $n$ . Non-trivial solutions exist only if the matrix $(A-\lambda I)v$  is singular which means $det(A-\lambda I)v=0$ . 

Therefore eigenvalues of $A$  are roots of the characteristic polynomial
$$p(\lambda)=det(A-\lambda I)$$

For example, let us consider a $2 X 2$ square matrix, 

$$A = \begin{bmatrix}  2 & 1 \\ 1	& 2	\\\end{bmatrix}$$.

Now let us take the determinant of $A − λI$, the characteristic polynomial of $A$ is,

$$|A - λI|  = \begin{bmatrix} 2 - λ & 1 \\ 1	& 2 - λ	\\\end{bmatrix} = 3 - 4λ + λ^2$$

In this example, setting the characteristic polynomial equal to zero, it has roots at $λ=1$ and $λ=3$, which are the two eigenvalues of $A$.

The eigenvectors corresponding to each eigenvalue can be found by solving for the components of $v$ in the below equation, 

$$(A-\lambda I)v=0$$

$v_{λ - 1}  = \begin{bmatrix} 1 \\ -1 \\\end{bmatrix}$ and $v_{λ - 3} = \begin{bmatrix} 1 \\ 1 \\\end{bmatrix}$.

**Eigenvalues and Eigenvectors using Python:**


SciPy provides a function in the library called `eig` to compute the Eigenvalue and the Eigenvector.

**Syntax to compute the Eigenvalue and the Eigenvector:** `scipy.linalg.eig(matrix)`

Let us find out eigenvalues and eigenvectors of a $2 \times 2$ matrix using `eig()` function:


In [ ]:
# S3.1: Find eigenvalues and eigenvectors using python
from scipy import linalg
import numpy as np
my_arr1 = np.array([[5,7],[11,3]])
eg_val, eg_vect = linalg.eig(my_arr1)
print("The Eigenvalues are :")
print(eg_val)
print("The Eigenvectors are :")
print(eg_vect)

The Eigenvalues are :
[12.83176087+0.j -4.83176087+0.j]
The Eigenvectors are :
[[ 0.66640536 -0.57999285]
 [ 0.74558963  0.81462157]]


In the above code:
- We have defined a matrix having certain values.
- The matrix is passed as a parameter to the `eig()` function that computes the eigenvalues and the eigenvectors of the matrix.
- The `eig()` function will return two values, first is eigenvalues and second is eigenvectors.

Similarly let us find out eigenvalues and eigenvectors of a $3 \times 3$ matrix using `eig()` function:

In [ ]:
# S3.2: Find eigenvalues and eigenvectors  of a 3 X 3 matrix using python.
from scipy import linalg
import numpy as np
my_arr2 = np.array([[1,2,3],[2, 3, 4], [4, 5, 6]])
eg_val, eg_vect = linalg.eig(my_arr2)
print("The Eigenvalues are :")
print(eg_val)
print("The Eigenvectors are :")
print(eg_vect)

The Eigenvalues are :
[ 1.08309519e+01+0.j -8.30951895e-01+0.j  1.01486082e-16+0.j]
The Eigenvectors are :
[[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]


In the above code:
- A $3 \times 3$ matrix is passed as a parameter to the `eig()` function that computes the eigenvalues and the eigenvectors of the matrix.

We will stop here. In the next class, we will learn to implement string matching algorithms.