<a href="https://colab.research.google.com/github/aadityasomani/Aadi/blob/master/Lesson_12_NumPy_Arrays_I_Aditya.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lesson 12: NumPy Arrays I


---

### Teacher-Student Tasks

In the previous lesson, we learned how to create a Python list using the list comprehension method. In this lesson, we are going to learn how to create NumPy arrays.

An array is also a data structure that contains multiple values. Working with NumPy arrays is much easier than working with Python lists.

The term NumPy stands for Numeric (or Numerical) Python. It is one of the most popular modules amongst Statisticians and Data Scientists across the globe to perform heavy mathematical computations. NumPy arrays are also faster than Python lists in terms of code execution time.

For all practical purposes, **an array is the same as a list**. Fundamentally, they have been programmed differently by the inventors of Python language. We are **NOT** required to know how they were created. We only need to know how to apply them in different situations.


---

#### Task 1: NumPy Arrays - The `ones()` and `zeros()` Functions

To get started with NumPy arrays, let's create an array having each item as `1` with dimensions `3` rows and `3` columns. 

To create such an array, you first need to `import` the `numpy` module at the beginning of the code. Then use the `ones()` function from the `numpy` module.

The `ones()` function requires two inputs. The first input should be the required dimension of the array and the second input should define the data type of the items in the required array. 


In [1]:
import numpy as np
# S1.1: Create an array containing '1' as its items using the 'ones()' function from the 'numpy' module.
ones=np.ones((3,3),dtype=int)
# Step 1: Always import the 'numpy' module at the beginning of the code and give it an alias (or nickname) called np. 
# We will always refer to the 'numpy' module as 'np' throughout the code.
ones
# Step 2: Call 'ones()' function from the np module using the dot operator.
# The 'ones()' function, requires two inputs: the dimension of the array and data type of the items which in this case is 'int'. 


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

**Note:** 

1. Always import the `numpy` module at the beginning of the code with `np` as its alias (or nickname). Throughout the course, we will always refer to the `numpy` module as `np` unless otherwise specified.

2. The de facto data type of an item in a NumPy array is `float`.

Using the `type()` function, you can verify whether an array is a NumPy array or not:

In [2]:
# S1.2: Using the 'type()' function, verify whether the 'ones' array is a NumPy array or not.
type(ones)

numpy.ndarray

As you can see, the `type()` function has returned `numpy.ndarray` as an output which confirms that the `ones` array is indeed a NumPy array. 

Similarly, you try to create a NumPy array having each item as `0` with dimensions `2` rows and `3` columns using the `zeros()` function. Make sure that each item is an integer:


In [3]:
# S1.3: Using 'zeros()' function, create a NumPy array having 2 rows and 3 columns. The items should be int data-type.
zeros=np.zeros((2,3),dtype=int)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

Recreate the above array without providing the data type as input. The output should be a two-dimensional array with each item as `0.` which is a floating-point number.


In [5]:
# S1.4: Using 'zeros()' function, create a numpy array having 2 rows and 3 columns.
zeros_float=np.zeros((2,3))
zeros_float

array([[0., 0., 0.],
       [0., 0., 0.]])

As you can see, all the items of the `zero_float` array are of `float` data type. 


---

#### Task 2: The `dtype` Keyword

To check the data type of the values stored in a NumPy array, you can use the `dtype` keyword:


In [6]:
# S2.1: Using the 'dtype' keyword, verify whether the 'zeros_float' array items are floating-point values or not. 
zeros_float.dtype

dtype('float64')

**Note:** For the time being ignore the number `64`.

As you can see, the `dtype` keyword has returned `dtype('float64')` as an output confirming that all the items of the `zeros_float` array are floating-point values: 


In [7]:
# S2.2: Using the 'dtype' keyword, verify whether the 'ones' array items are int values or not. 
ones.dtype

dtype('int64')

For the time being ignore the number `64`. As you can see, the `dtype` keyword has returned `dtype('int64')` as an output confirming that all the items of the `ones` array are integer values. 
 

**Difference between the `type()` function and the `dtype` keyword**

The `type()` function is a function of Python. It returns the type of Python object. The data types or more accurately the **primitive data types** `int`, `float`, `str`, and `bool` are Python objects. Similarly, Python lists, NumPy modules, `random` modules are also Python objects. The `type()` function will tell you what type of Python objects they are:

In [ ]:
# S2.3: Run the code shown below to see that the 'type()' function returns the type of Python object.


In the output, ignore the term `class`. We will explore this term in more detail in the upcoming classes.

As you can see, the `type()` function indeed returns the type of Python object for an entity in Python.

---

#### Task 3: The `ndim` and `shape` Keywords

**The `ndim` keyword:** Using the `ndim` keyword, you can find out the dimension of a NumPy array. The `ones`, `zeros`, and `zeros_float` arrays are two-dimensional arrays. So, the `ndim` keyword should return `2` for each of these arrays.

In [10]:
# S3.1: Using the 'ndim' array, find out the dimension of 'ones', 'zeros', and 'zeros_float' NumPy arrays.
print(ones.ndim)
print(zeros.ndim)
zeros_float.ndim

2
2


2

**The `shape` keyword:** Using the `shape` keyword, you can find out the number of rows and columns present in NumPy arrays.

In [11]:
# S3.2: Using the 'shape' keyword find out the number of blocks, rows, and columns in the 'ones', 'zeros', and 'zeros_float' arrays.
print(ones.shape)
print(zeros.shape)
zeros_float.shape

(3, 3)
(2, 3)


(2, 3)

From the above output, we can conclude that:

- The `ones` array has 3 rows and 3 columns.

- The `zeros` array has 2 rows and 3 columns.

- The `zeros_ones` array also has 2 rows and 3 columns.

---

#### Task 4: The `arange()` and `linspace()` Functions

There are `arange()` and `linspace()` functions in NumPy module create an array of numbers such that the difference between a pair of any two consecutive numbers in the array is constant. However, there is a slight difference in their outputs.

**The `arange()` function:** It returns a one-dimensional array containing numbers between two specific numbers. It is similar to the `range()` function in the `for` loop.

In [13]:
# S4.1: Create a one-dimensional array containing numbers between 5 and 20 using the 'arange()' function in the NumPy module.
arr1=np.arange(5,21)
arr1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

Here, the `arange()` function has created an array of numbers from `5` to `20`. The difference between a pair of any two consecutive numbers is `1`. The `arange()` function will not include the last number specified in the array created.

If you want the difference between two consecutive numbers to be greater than `1` (say `4`) in an array, then you can specify the difference as an additional input to the `arange()` function.

In [15]:
# S4.2: Create an array of numbers from 1 to 24 such that the difference between two consecutive numbers is 4.
arr2=np.arange(1,25,4)
arr2

array([ 1,  5,  9, 13, 17, 21])

As you can see, the `arange()` function has created an array of numbers from `1` to `24` such that the difference between two consecutive numbers is `4`. 

**Note:** If the difference between two consecutive numbers is not specified, then the `arange()` function will assume that the difference is `1`.

You can also create an array containing the floating-point numbers using the `arange()` function by providing `dtype=float` as an additional input to the function.

In [18]:
# S4.3: Create an array of numbers from 1 to 24 such that the difference between two consecutive numbers is 4 and each item is a float.
arr3=np.arange(1,25,4,dtype=float)
arr3

array([ 1.,  5.,  9., 13., 17., 21.])

As you can see, the items contained in `array3` are floating-point numbers.

**The `linspace()` function:** This function creates an array containing a fixed number of numbers between two specific numbers such that the difference between any two consecutive numbers in the array is constant. This will be clear to you with an example.

Suppose you want to create an array containing exactly `4` numbers between the numbers `1` and `25` such that all the difference between any two consecutive numbers is constant, then you can use the `linspace()` function.

In [19]:
# S4.4: Create an array containing 4 numbers between 1 to 25.
array4 = np.linspace(1, 25, 5)
array4

array([ 1.,  7., 13., 19., 25.])

As you can see, the `linspace()` function has created an array containing `4` numbers between `1` and `25` (including `25`) such that the difference between two consecutive numbers is constant. Take a pair of any two consecutive numbers in `array5`, the difference between them will be `8.`

**Note:** Notice the difference between the outputs of the `arange()` and `linspace()` functions for the same inputs. The `arange()` function returns `6` numbers such that the difference between them is exactly `4` whereas the `linspace()` function returns exactly `4` numbers such that the difference between two consecutive numbers is constant. 

In other words:

- In the `arange()` function, you specify the value of the difference between two consecutive numbers as the third input.

- Whereas, in the `linspace()` function, you specify the length of the array to be created as the third input.

Let's create another array using the `linspace()` function to get a better understanding. Let's create an array containing `10` numbers between `1` and `25` such that the difference between two consecutive numbers is constant. 


In [22]:
# S4.5: Create an array containing 10 numbers between 1 and 25 such that the difference between two consecutive numbers is constant.
arr5=np.linspace(1,25,10)
arr5

array([ 1.        ,  3.66666667,  6.33333333,  9.        , 11.66666667,
       14.33333333, 17.        , 19.66666667, 22.33333333, 25.        ])

Take a pair of any two consecutive numbers in the `array5`, the difference between them will be `2.66666666`

---

#### Task 5: The `reshape()` Function


The `reshape()` function reshapes an array from one configuration to another without changing the items.

The `zeros` array has 2 rows and 3 columns. Suppose you want to reshape it into another array having `6` rows and `4` columns without changing the items, then you can use the `reshape()` function:

In [25]:
# S5.1: Reshape the 'zeros' array so that it has 6 rows and 4 columns.
zeros=np.zeros(24,dtype=int)
reshape_zeros=zeros.reshape(6,4)
print(zeros)
reshape_zeros

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

The `reshape()` function has reshaped the `zeros` array to a two-dimensional array having 3 rows and 2 columns. Inside the `reshape()` function, you have to provide the new configuration. 

This operation is only valid when the number of items in the new configuration is the same as the number of items in the original configuration. 

In this case, there are 6 items  in the original configuration. So the new configuration must also have 6 items.


---

#### Task 6: The `ndarray()` Function
In general, we can create a NumPy array containing some random values using `ndarray()` function.

Let's say we want to create a NumPy array having some random integer values which have 5 rows and 2 columns, then you can use the `ndarray()` function.

Similar to the `zeros()` and `ones()` functions, the `ndarray()` function takes two inputs: the first input is the configuration of the required array and the second input is the data type of items. The de facto data type is a floating-point value:

In [30]:
# S6.1: Create a 'numpy' array using 'ndarray()' function having 5 rows and 2 columns.
arr6=np.ndarray((5,2),dtype=int)
arr6

array([[94759332833072,   446676598899],
       [  481036337249,   408021893221],
       [  433791697018,   476741369970],
       [  261993005171,            122],
       [             0,              0]])

From the above output, you may observe that the `ndarray()` function has created an array of desired shapes containing random integers.



---

#### Task 7: The `random.randint()` Function

The NumPy module also has its `random.randint()` function. It takes two inputs. The first input is the range of two integers between which a random number is to be created. The second input is the `size` parameter which defines the number of random integers to be created.

**Syntax:** `np.random.randint(num1, num2, size=N)`
 
 Where `num1` and `num2` are starting numbers and `N` is the number of items to be contained in the array.

In [32]:
# S7.1: Create a one-dimensional NumPy array containing 15 random integers between 50 and 100.
import random
arr7_1d=np.random.randint(50,100,size=15)
arr7_1d

array([51, 92, 66, 67, 91, 63, 86, 60, 83, 63, 88, 73, 92, 82, 75])

Similarly, you can create a multi-dimensional NumPy array containing random integers by specifying the dimensions of the array to be created in the `size` parameter:

In [33]:
# S7.2: Create a two-dimensional NumPy array containing 15 random integers between 50 and 100.
arr7_2d=np.random.randint(50,100,size=(3,5))
arr7_2d

array([[70, 92, 77, 92, 85],
       [95, 58, 88, 51, 79],
       [90, 52, 72, 93, 62]])

In [34]:
arr7_2d[0][0]

70

In this way, you can generate one-dimensional and two-dimensional arrays containing random numbers within a specific range using `random.randint()` function.

---

#### Task 8: The `array()` Function


We can convert a Python list into a NumPy array. To do this, use the `array()` function which takes a Python list as an input.

Let's first create a list of natural numbers from `1` to `15` using the list comprehension method. Then convert the list into a NumPy array using the `array()` function:

In [38]:
# S8.1: Convert a Python list into a NumPy array using the 'array()' function.
lst=[i for i in range(1,16)]
print(lst)
array9=np.array(lst)
array9

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

To check whether a Python list is converted into a NumPy array or not, you can use the `type()` function:

In [40]:
# S8.2: Verify whether the 'arr' array is a NumPy array or a Python list.
print(type(lst))
array9.dtype

<class 'list'>


dtype('int64')

From the above output, we observe that we have successfully created a NumPy `ndarray` object from a Python list using the `array()` function.

---

#### Task 9: The `list()` Function

We can convert a NumPy array into a Python list using the `list()` function.

Let's convert the `arr` NumPy array into a Python list using the `list()` function:

In [41]:
# S9.1: Convert a NumPy array into a Python list using the 'list()' function.
lst2=list(array9)
lst2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

Let's verify whether the conversion happened or not using the `type()` function:

In [42]:
# S9.2: Verify whether the 'arr_converted' list is a Python list or not.
type(lst2)

list

As you can see, the output is a `list`. Hence, we successfully converted the NumPy array to a Python list using the `list()` function.

---

#### Task 10: The `sqrt()` Function

One of the most notorious concepts in maths is Heron's formula. It calculates the area of a triangle having sides $a, b, \space \text{and} \space c$.

<img src='https://drive.google.com/uc?id=18SFm-ovV_QnKufMNNaXB6aWhIhT1cVki' width=500>

According to Heron's formula, the area of a triangle is given by.

$$\text{Area} = \sqrt{s(s-a)(s-b)(s-c)}$$

Where,
$$s = \frac{a + b + c}{2}$$

i.e., the semi-perimeter of a triangle.

Let's create a function that takes the lengths of the sides of a triangle and checks whether the lengths indeed represent the lengths of the sides of a triangle.

*The sum of lengths of any two sides of a triangle is always greater than the length of the third side.*

If the lengths meet the criteria for being the lengths of the sides of a triangle, then the function should return `True`. Else it should return `False`.

In [43]:
# S10.1: Create a function to check whether the input lenghts represent the lengths of the side of a triangle.
def is_triangle(a,b,c):
    if a+b>c and a+c>b and b+c>a:
        return True
    else:
        return False

Now, let's create a function to calculate the area of a triangle using Heron's formula. The function must include the `is_triangle()` function and `np.sqrt()` functions. If the invalid side lengths are passed as input to the function, then it should return an `Invalid triangle.` message else it should return the area of a triangle.


In [59]:
# S10.2: Create a function to calculate the area of a triangle using Heron's formula.
def herons_formula(a,b,c):
   # if is_triangle(a,b,c):
        s=(a+b+c)/2
        
        return np.sqrt(s*(s-a)*(s-b)*(s-c))
        #return (s*(s-a)*(s-b)*(s-c))**0.5
   # else:
        print("Invalid Triangle.")
herons_formula(-3,4,5)

0.0

In [62]:
np.sqrt(-9)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


nan

Alternatively, you can raise a number to the power `0.5` to calculate the square root of a number, but it will return a complex number as an output for a negative number. On the other hand, the `np.sqrt()` function returns `nan` for negative numbers. It stands for **not a number** and denotes a NumPy null value.

We will stop here. Thus, in this class, we learned how to create a NumPy array and some basic NumPy functions. In the next class, we will learn to create three-dimensional arrays and also explore the Claude Shannon Mind Reading algorithm.

---

In [73]:
arr=np.arange(1,13).reshape(6,2)
print(arr)
rev_arr=arr[::-1,::-1].reshape(2,6)
rev_arr
arr_trans=arr.reshape(2,6)
arr_trans

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])